apiVersion: v2
name: nidhogg
description: A proxy chart for nidhogg
type: application
version: 1.0.3

maintainers:
  - name: MadsHT

dependencies:
  - name: nidhogg
    version: "v1.0.1"
    repository: "https://distributed-technologies.github.io/helm-repository/"
