---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: az-base-template
spec:
  entrypoint: az-base
  arguments:
    parameters:
      - name: sp-secret-name
        value: service-principal
  templates:
  - name: az-base
    inputs:
      parameters:
      - name: script
      - name: sp-secret-name
        default: service-principal
    container:
      image: mcr.microsoft.com/azure-cli
      command: ["/bin/sh", "-c"]
      args:
        - |
          az login --service-principal -u $sp_client_id -p $sp_client_secret --tenant $sp_tenant_id --output none;
          az account set --subscription $sp_subscription_id

          {{`{{inputs.parameters.script}}`}}
      env:
        - name: sp_client_id
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: clientid
        - name: sp_client_secret
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: clientsecret
        - name: sp_subscription_id
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: subscriptionid
        - name: sp_tenant_id
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: tenantid
