name: argo-events-setup
clusterService: false
namespace: argo-events
description: Argo events setup

project:
  name: argo-events-setup
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: argo-events-setup
    source:
      repoURL: "https://github.com/Open-Dataplatform/argo-events-setup.git"
      targetRevision: HEAD
      path: setup
      valuesFile: "argo-events-setup.yaml"
  - name: argo-events-github
    source:
      repoURL: "https://github.com/Open-Dataplatform/argo-events-setup.git"
      targetRevision: HEAD
      path: events-github
      valuesFile: "argo-events-github.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      host: service-poc.westeurope.cloudapp.azure.com
      routes:
      - kind: Rule
        # Without host
        match: PathPrefix(`/argo-events/github`)
        services:
          - name: github-pr-eventsource-svc
            port: 12000
      certificate:
        enabled: true

  - name: argo-events-azure
    source:
      repoURL: "https://github.com/Open-Dataplatform/argo-events-setup.git"
      targetRevision: HEAD
      path: events-azure
      valuesFile: "argo-events-azure.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      host: service-poc.westeurope.cloudapp.azure.com
      routes:
      - kind: Rule
        # Without host
        match: PathPrefix(`/argo-events/azure`)
        services:
          - name: azure-webhook-eventsource-svc
            port: 12000
      certificate:
        enabled: true
