apiVersion: v2
name: traefik-forward-auth
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
- name: lethe
  version: "0.0.2"
  repository: https://open-olympus-project.github.io/repo-helm/