apiVersion: v2
name: traefik-forward-auth
description: A proxy chart for traefik-forward-auth
type: application
version: 0.1.5

maintainers:
  - name: MadsHT

dependencies:
- name: lethe
  version: "0.1.0"
  repository: https://open-olympus-project.github.io/repo-helm/
- name: janus
  version: "0.1.1"
  repository: https://open-olympus-project.github.io/repo-helm/
  condition: janus.enabled
