apiVersion: v2
name: prometheus
description: A proxy chart for prometheus
type: application
version: 0.1.5

maintainers:
  - name: MadsHT

dependencies:
- name: prometheus
  version: "14.6.0"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: prometheus-pushgateway
  version: "1.10.1"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: standalonePushgateway.enabled
- name: lethe
  version: "0.1.0"
  repository: https://open-olympus-project.github.io/repo-helm/
