standalonePushgateway:
  enabled: false

# prometheus-pushgateway:

# prometheus:

lethe:
  secretStores:
    - name: vault-backend
      providers:
        vault:
          server: "http://vault.tooling.svc:8200"
          path: "k8s"
          version: "v2"
          auth:
            # Authenticate against Vault using a Kubernetes ServiceAccount
            # token stored in a Secret.
            # https://www.vaultproject.io/docs/auth/kubernetes
            kubernetes:
              # Path where the Kubernetes authentication backend is mounted in Vault
              mountPath: "kubernetes"
              # A required field containing the Vault Role to assume.
              role: "k8s-secrets"
  secrets:
    - name: prometheus-bucket
      secretStore:
        backend: vault-backend
        kind: SecretStore
      target:
        name: prometheus-bucket
        template:
          data:
            object-store.yaml: |
              type: AZURE
              config:
                storage_account: "{{ .saName | toString }}"
                storage_account_key: "{{ .saKey | toString }}"
                container: "thanos"
                endpoint: ""
                max_retries: 3
      data:
        - secretKey: saName
          remoteRef:
            key: secrets/sa-metrics
            property: sa-name
        - secretKey: saKey
          remoteRef:
            key: secrets/sa-metrics
            property: sa-key

janus:
  # These will be changed in Yggdrasil
  host: host
  certmanagerIssuer:
    kind: issuer-kind
    name: issuer-name

  ingressRoutes:
    - name: prometheus
      # annotations:
      entryPoints:
        - websecure
      host: host
      routes:
      - kind: Rule
        # Without host
        match: PathPrefix(`/alertmanager`)
        services:
          - name: prometheus-alertmanager
            port: 80
        middlewares:
          - name: auth
            namespace: networking
      certificate:
        enabled: true
