apiVersion: v2
name: argo-events
description: A proxy chart for argo-events
type: application
version: 0.1.1

maintainers:
  - name: MadsHT

dependencies:
- name: argo-events
  repository: "https://argoproj.github.io/argo-helm"
  version: "1.4.0"