---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terraform-base-tp
spec:
  entrypoint: terraform-base
  templates:
  - name: terraform-base
    inputs:
      artifacts:
      - name: terraform-folder
        path: /src
      parameters:
      - name: sp-secret-name
        default: service-principal
      - name: terraform-path
      - name: action
      - name: args
    container:
      image: hashicorp/terraform:0.14.11
      command: ["/bin/sh", "-c"]
      args:
        - |
          terraform {{`{{inputs.parameters.action}}`}} {{`{{inputs.parameters.args}}`}} {{`{{inputs.parameters.terraform-path}}`}}
      workingDir: /src
      env:
        - name: ARM_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: clientid
        - name: ARM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: clientsecret
        - name: ARM_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: subscriptionid
        - name: ARM_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: '{{`{{inputs.parameters.sp-secret-name}}`}}-secret'
              key: tenantid

    outputs:
      artifacts:
      - name: terraform-folder
        optional: true
        path: '/src'
      - name: kube-config
        optional: true
        path: '/src/config'
      - name: values
        optional: true
        path: '/src/values'
      parameters:
      - name: fqdn
        valueFrom:
          default: ''
          path: '/src/fqdn'
      - name: fqdn_vault
        valueFrom:
          default: ''
          path: '/src/fqdn_vault'
      - name: cluster_name
        valueFrom:
          default: ''
          path: '/src/cluster_name'
      - name: cluster_fqdn
        valueFrom:
          default: ''
          path: '/src/cluster_fqdn'