argo-workflows:
  server:
    enabled: true
    # only updates base url of resources on client side,
    # it's expected that a proxy server rewrites the request URL and gets rid of this prefix
    # https://github.com/argoproj/argo-workflows/issues/716#issuecomment-433213190
    baseHref: /argowf/
    secure: false
    #TODO delete this when oidc comes into play
    extraArgs:
    - --auth-mode=client
  controller:
    containerRuntimeExecutor: pns
    workflowNamespaces:
      - tooling
      - argo-events
    
    workflowDefaults:
      spec:
        serviceAccountName: argo-workflow

  workflow:
    serviceAccount:
      create: true
      name: "argo-workflow"
    rbac:
      create: true
  
  useDefaultArtifactRepo: true
  artifactRepository:
    # archiveLogs will archive the main container logs as an artifact
    archiveLogs: true
    s3:
      # Note the `key` attribute is not the actual secret, it's the PATH to
      # the contents in the associated secret, as defined by the `name` attribute.
      accessKeySecret:
        name: minio-creds-secret
        key: accesskey
      secretKeySecret:
        name: minio-creds-secret
        key: secretkey
      insecure: true
      bucket: argo-artifacts
      endpoint: minio.tooling:9000