{{- range .Values.services -}}
{{- if .enabled -}}

{{ $tcpPorts := dict }}
{{ $udpPorts := dict }}
{{- range $name, $config := $.Values.traefik.ports }}
  {{- if eq (toString $config.protocol) "UDP" }}
    {{ $_ := set $udpPorts $name $config }}
  {{- else }}
    {{ $_ := set $tcpPorts $name $config }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: List
metadata:
  name: {{ include "traefik.fullname" $ }}
items:
{{- if  $tcpPorts }}
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "traefik.fullname" $ }}{{ .namePrefix }}
      labels:
        app.kubernetes.io/name: {{ include "traefik.name" $ }}
        helm.sh/chart: {{ include "traefik.chart" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- with $.Values.traefik.service.labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with (merge .annotationsTCP .annotations) }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- $type := default "LoadBalancer" .type }}
      type: {{ $type }}
      {{- with .spec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      selector:
        app.kubernetes.io/name: {{ include "traefik.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
      ports:
      {{- range $name, $config := $tcpPorts }}
      {{- if $config.expose }}
      - port: {{ default $config.port $config.exposedPort }}
        name: {{ $name }}
        targetPort: {{ $name | quote }}
        protocol: {{ default "TCP" $config.protocol | quote }}
        {{- if $config.nodePort }}
        nodePort: {{ $config.nodePort }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if eq $type "LoadBalancer" }}
      {{- with .loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
      {{- end -}}
      {{- with .externalIPs }}
      externalIPs:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
{{- end }}

{{- if  $udpPorts }}
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "traefik.fullname" $ }}-udp
      labels:
        app.kubernetes.io/name: {{ include "traefik.name" $ }}
        helm.sh/chart: {{ include "traefik.chart" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- with $.Values.treafik.service.labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with (merge .annotationsUDP .annotations) }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- $type := default "LoadBalancer" .type }}
      type: {{ $type }}
      {{- with .spec }}
      {{- toYaml . | nindent 6 }}   
      {{- end }}
      selector:
        app.kubernetes.io/name: {{ include "traefik.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
      ports:
      {{- range $name, $config := $udpPorts }}
      {{- if $config.expose }}
      - port: {{ default $config.port $config.exposedPort }}
        name: {{ $name }}
        targetPort: {{ $name | quote }}
        protocol: {{ default "UDP" $config.protocol | quote }}
        {{- if $config.nodePort }}
        nodePort: {{ $config.nodePort }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if eq $type "LoadBalancer" }}
      {{- with .loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
      {{- end -}}
      {{- with .externalIPs }}
      externalIPs:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
{{- end }}
{{- end -}}
{{- end -}}
