name: monitoring
clusterService: true
namespace: monitoring
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.

project:
  name: monitoring
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: rook-ceph
      server: https://kubernetes.default.svc

apps:
  - name: prometheus
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.4
      chart: "prometheus"
      valuesFile: "prometheus.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      host: service-poc.westeurope.cloudapp.azure.com
      routes:
      - kind: Rule
        # Without host
        match: PathPrefix(`/alertmanager`)
        services:
          - name: prometheus-alertmanager
            port: 80
        middlewares:
          - name: auth
            namespace: networking
      certificate:
        enabled: trues

  - name: thanos
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.4
      chart: "thanos"
      valuesFile: "thanos.yaml"
  - name: grafana
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.1
      chart: "grafana"
      valuesFile: "grafana.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      host: service-poc.westeurope.cloudapp.azure.com
      routes:
      - kind: Rule
        match: PathPrefix(`/grafana`)
        services:
          - name: grafana
            port: 80
        middlewares:
          - name: auth
            namespace: networking
          - name: grafana-stripprefix
      middlewares:
      - name: grafana-stripprefix
        spec:
          stripPrefix:
            prefixes:
              - /grafana
      certificate:
        enabled: true

  - name: loki
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.0
      chart: "loki-stack"
      valuesFile: "loki.yaml"
  - name: jaeger-operator
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.1
      chart: "jaeger-operator"
      valuesFile: "jaeger-operator.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      host: service-poc.westeurope.cloudapp.azure.com
      routes:
      - kind: Rule
        match: PathPrefix(`/jaeger`)
        services:
          - name: jaeger-operator-jaeger-query
            port: 16686
        middlewares:
          - name: auth
            namespace: networking
      certificate:
        enabled: true
