jaeger-operator:
  jaeger:
    # Specifies whether Jaeger instance should be created
    create: true

    spec: 
      strategy: allInOne
      allInOne:
        options:
          query:
            base-path: /jaeger
      
      storage:
        options:
          memory:
            max-traces: 100000
    
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # nodeSelector:
  #   agentpool: monitoring

  rbac:
    # Specifies whether RBAC resources should be created
    create: true
    pspEnabled: false
    clusterRole: true