apiVersion: v2
name: thanos
description: A proxy chart for thanos
type: application
version: 0.1.1

maintainers:
  - name: MadsHT

dependencies:
- name: thanos
  version: "0.4.5"
  repository: "https://kubernetes-charts.banzaicloud.com"
- name: lethe
  version: "0.0.2"
  repository: https://open-olympus-project.github.io/repo-helm/
