#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.saName }}
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: DEFAULT_PROVIDER
          value: "oidc"
        - name: LOG_LEVEL
          value: "trace"
        - name: COOKIE_DOMAIN
          value: {{ .Values.appHost | quote}}
        - name: AUTH_HOST
          value: {{ .Values.authHost | quote }}
{{ .Values.deployment.env | toYaml | indent 8}}
