---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: sso-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: sso-secret-backend
    kind: SecretStore
  data:
  - secretKey: issuerurl
    remoteRef:
      key: secrets/sso
      property: issuerurl
  - secretKey: clientid
    remoteRef:
      key: secrets/sso
      property: clientid
  - secretKey: clientsecret
    remoteRef:
      key: secrets/sso
      property: clientsecret
  - secretKey: jwtsecret
    remoteRef:
      key: secrets/sso
      property: jwtsecret
  target:
    name: sso-secret
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: sso-secret-backend
spec:
  provider:
    vault:
      server: "http://vault.tooling.svc:8200"
      path: "k8s"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "k8s-secrets"