apiVersion: v2
name: janus
description: A Helm chart that is used to build ingressRoutes, middleware and certificates.
type: application
version: 0.1.3

maintainers:
  - name: MadsHT

annotations:
  changeLog: |
    - [0.1.2] added optional host key to Route list that will override the global key
