{{- $root := . }}
{{- range $path, $_ := .Files.Glob "**/**/config.yaml" }}
  {{- $project := $root.Files.Get $path | fromYaml }}
  {{- range $project.apps }}
    {{ $app := . }}
    {{- if get $root.Values.applications .name -}}
      {{- if .ingressRoute }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}-ingress-route
  namespace: {{ $project.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints:
{{ .ingressRoute.entryPoints | toYaml | indent 4 }}
  routes:
{{- range .ingressRoute.routes}}
  - kind: {{ .kind }}
    match: Host(`{{ $app.ingressRoute.host }}`) {{ if .match }}{{ printf "%s %s" "&&" .match }}{{ end }}
    services:
{{ .services | toYaml | indent 6 }}
    middlewares:
{{ .middlewares | toYaml | indent 6 }}
{{- end }}
  tls:
    secretName: {{ .name }}-tls

{{ range .ingressRoute.middlewares }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ $project.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
{{ .spec | toYaml | indent 2 }}
{{ end }}

{{ if .ingressRoute.certificate.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-tls
  namespace: {{ $project.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dnsNames:
    - {{ $app.ingressRoute.host }}
  secretName: {{ .name }}-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ $root.Values.ingress.certmanagerissuer }}
{{ end }}

      {{ end }}
    {{ end }}
  {{ end }}
{{ end }}
