apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress-route
  namespace: nidhogg
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ (first .Values.ingress.hosts).host }}`) && PathPrefix(`/argocd`)
      priority: 10
      services:
        - name: nidhogg-argocd-server
          port: 80
    - kind: Rule
      match: Host(`{{ (first .Values.ingress.hosts).host }}`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: nidhogg-argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: nidhogg
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dnsNames:
    - {{ (first .Values.ingress.hosts).host }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.ingress.certmanagerissuer }}
  secretName: argocd-tls