{{ $root := . }}
{{- range $secret, $_ := .Values.secretStores }}
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ .name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
{{- with .providers }}
  provider:
{{ . | toYaml | indent 4 }}
{{- end -}}

{{ end }}
