{{ $root := . }}
{{- range $secret, $_ := .Values.secretStores }}
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
{{- with .providers }}
  provider:
{{ . | toYaml | indent 4 }}
{{- end -}}

{{ end }}
