apiVersion: v2
name: traefik-forward-auth
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
- name: lethe
  version: "0.0.1"
  repository: https://github.com/Open-Olympus-Project/utility-lethe.git