apiVersion: v2
name: loki-stack
description: A proxy chart for loki and promtail
type: application
version: 0.2.6

maintainers:
  - name: MadsHT

dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.6.0"
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^3.7.0"
- name: janus
  version: "0.1.1"
  repository: https://open-olympus-project.github.io/repo-helm/
  condition: janus.enabled
- name: lethe
  version: "0.1.2"
  repository: https://open-olympus-project.github.io/repo-helm/
  condition: lethe.enabled
