---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argocd-vault-admin
spec:
  entrypoint: argocd-base
  templates:
  - name: argocd-base
    inputs:
      parameters:
      - name: server-url
      - name: script
      artifacts:
      - name: value
        optional: true
        path: /value.yaml
      - name: kube-config
        optional: true
        path: /.kube/config
      - name: argocd
        path: /bin/argocd
        mode: 0755
        http:
          url: 'https://github.com/argoproj/argo-cd/releases/download/v1.8.1/argocd-linux-amd64'
      - name: kubectl
        path: /bin/kubectl
        mode: 0755
        http:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
    retryStrategy:
      limit: 10
      backoff:
        duration: "30"       # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
        factor: 2
        maxDuration: "10m" # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
    container:
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - >
          export KUBECONFIG=/.kube/config;
          argocd login {{`{{inputs.parameters.server-url}}`}} --insecure --username $username --password $password;
          {{`{{inputs.parameters.script}}`}}
      env:
      - name: ARGOCD_OPTS
        value: '--grpc-web-root-path /argocd'
      - name: username
        valueFrom:
          secretKeyRef:
            name: 'argocd-creds'
            key: username
      - name: password
        valueFrom:
          secretKeyRef:
            name: 'argocd-creds'
            key: password