apiVersion: v2
name: argo-wf
description: A Helm chart for Kubernetes
type: application
version: 0.1.1

maintainers:
  - name: MadsHT

dependencies:
- name: argo-workflows
  version: "0.4.1"
  repository: "https://argoproj.github.io/argo-helm"
- name: lethe
  version: "0.0.2"
  repository: "https://open-olympus-project.github.io/repo-helm/"
