argo-workflows:
  server:
    secure: false
    extraArgs:
      - --auth-mode=sso
    sso:
      clientId:
        name: argowf-sso
        key: clientid
      clientSecret:
        name: argowf-sso
        key: clientsecret
      scopes:
        - openid
        - profile
        - email

  controller:
    containerRuntimeExecutor: pns
    workflowDefaults:
      spec:
        serviceAccountName: argo-workflow
        # must complete in 8h (28,800 seconds)
        activeDeadlineSeconds: 28800
        # keep workflows for 1d (86,400 seconds)
        ttlStrategy:
          secondsAfterCompletion: 86400
        # delete all pods as soon as they complete
        podGC:
          strategy: OnPodCompletion

  workflow:
    serviceAccount:
      create: true
      name: "argo-workflow"
    rbac:
      create: true
  useDefaultArtifactRepo: true
  artifactRepository:
    # archiveLogs will archive the main container logs as an artifact
    archiveLogs: true
    s3:
      # Note the `key` attribute is not the actual secret, it's the PATH to
      # the contents in the associated secret, as defined by the `name` attribute.
      key: objects/download/
      accessKeySecret:
        name: minio-creds-secret
        key: accesskey
      secretKeySecret:
        name: minio-creds-secret
        key: secretkey
      insecure: true
      bucket: argo-artifacts
      endpoint: minio.tooling.svc

lethe:
  enabled: false
