apiVersion: v2
name: grafana
description: A proxy chart for grafana
type: application
version: 0.1.1

maintainers:
  - name: MadsHT

dependencies:
- name: grafana
  version: "5.6.5"
  repository: "https://grafana.github.io/helm-charts"