{{- define "athena.configmap.yaml" -}}
apiVersion: v1
kind: ConfigMap
data: {}
{{- end -}}
{{- define "athena.configmap" }}
{{- include "athena.util.merge" (append . "athena.configmap.yaml") -}}
{{- end -}}
