{{/*
athena.helper.name
Will generate a meaningful name
*/}}
{{- define "athena.helper.name" }}
{{- printf "%s-%s" .context.Chart.Name .name }}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "athena.helper.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
athena.helper.labels
Will generate common labels
*/}}
{{- define "athena.helper.labels" }}
helm.sh/chart: {{ include "athena.helper.chart" .context }}
app.kubernetes.io/managed-by: {{ .context.Release.Service }}
{{- end -}}

{{/*
athena.helper.selectorLabels
Will generate selector labels
*/}}
{{- define "athena.helper.selectorLabels" -}}
{{- if .name -}}
app.kubernetes.io/name: {{ include "athena.helper.name" (dict "context" .context "name" .name) }}
{{ end -}}
app.kubernetes.io/instance: {{ .context.Release.Name }}
{{- if .component }}
app.kubernetes.io/component: {{ .component }}
{{- end }}
{{- end }}

{{/*
athena.helper.metadata
Will generate a metdata based on context
*/}}
{{- define "athena.helper.metadata" }}
metadata:
  name: {{ template "athena.helper.name" (dict "context" .context "name" .name) }}
  labels:
{{ include "athena.helper.labels" (dict "context" .context) | indent 4 }}
{{ include "athena.helper.selectorLabels" (dict "context" .context "name" .name) | indent 4 }}
{{- end -}}
