{{ range .Values.issuers }}
{{ if .enabled }}
---
apiVersion: cert-manager.io/v1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .email }}
    server: {{ .server}}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{ .privateKeySecretRef }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
{{ .solvers | toYaml | indent 4}}
{{ end }}
{{ end }}