apiVersion: v2
name: jaeger-operator
description: A proxy chart for jaeger-operator
type: application
version: 0.1.2

maintainers:
  - name: MadsHT

dependencies:
- name: jaeger-operator
  version: "2.21.0"
  repository: "https://jaegertracing.github.io/helm-charts"
- name: janus
  version: "0.1.1"
  repository: https://open-olympus-project.github.io/repo-helm/
