# jaeger-operator:

janus:
  # These will be changed in Yggdrasil
  host: host
  certmanagerIssuer:
    kind: issuer-kind
    name: issuer-name

  ingressRoutes:
    - name: prometheus
      # annotations:
      entryPoints:
        - websecure
      host: host
      routes:
      - kind: Rule
        # Without host
        match: PathPrefix(`/jaeger`)
        services:
          - name: jaeger-operator-jaeger-query
            port: 16686
        middlewares:
          - name: auth
            namespace: networking
      certificate:
        enabled: true
