---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-clone-template
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      parameters:
      - name: url
      - name: branch
        default: HEAD
    container:
      image: alpine/git
      command:
        - /bin/sh
        - -c
      args:
      - |
        echo "Starting git clone";
        ls /ssh-key
        mkdir ~/.ssh
        mv /ssh-key/* ~/.ssh/
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts;
        git clone -b "{{`{{inputs.parameters.branch}}`}}" "{{`{{inputs.parameters.url}}`}}" /repo;
        ls /repo;
      volumeMounts:
        - name: odp-github-ssh
          mountPath: "/ssh-key"
    volumes:
      - name: odp-github-ssh
        secret:
          secretName: odp-github-ssh
    outputs:
      artifacts:
      - name: repo
        optional: false
        path: /repo