---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-clone-template
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      parameters:
      - name: ssh-url
      - name: branch
        default: HEAD
    container:
      image: alpine/git
      command:
        - /bin/sh
        - -c
      args:
      - >
        mkdir ~/.ssh;
        touch ~/.ssh/known_hosts;
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts;
        mv /vault/secrets/* ~/.ssh;
        chmod -R 600 ~/.ssh;
        git clone -b "{{`{{inputs.parameters.branch}}`}}" "{{`{{inputs.parameters.ssh-url}}`}}" /repo;
    outputs:
      artifacts:
      - name: repo
        optional: true
        path: /repo